version: "3.3"
services:      
  app:
    build: ./b
    command: bash -c "uvicorn api.main:app --host 0.0.0.0 --reload & celery -A api.worker worker --loglevel=info"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
      - ./tmp:/app/tmp
  redis:
    image: "redis:alpine"
